### PR TITLE
Fixed non-working, autogenerated example and added a new one

### PR DESCRIPTION
**Pull request by merill**
﻿

Fixes #

### Changes proposed in this pull request

- Fixed non-working, autogenerated example and added a new one

### Other links

-
-
-

### CODE REVIEW

**Comment by timayabi2020** [comment]
@merill thanks for noticing this issue.  Here are my suggestions for the example to work as expected.
1.  Roll back to the previous example 1 title.
2.  Since you are targeting to merge into "dev" branch which is responsible for [V1 releases](https://www.powershellgallery.com/packages/Microsoft.Graph/1.28.0), we don't need "-MgBeta" prefix on cmdlets.  Cmdlets with that prefix are only available on [V2 releases](https://www.powershellgallery.com/packages/Microsoft.Graph/2.0.0-rc3) and the branch responsible is "features/2.0".So remove this ``New-MgBetaEntitlementManagementConnectedOrganization -DomainName microsoft.com``.
3.  Update $params with below.
```
$params = @{
	displayName = "Connected organization name"
	description = "Connected organization description"
	identitySources = @(
		@{
			"@odata.type" = "#microsoft.graph.domainIdentitySource"
			domainName = "example.com"
			displayName = "example.com"
		}
	)
	state = "proposed"
}
```
Check Api reference [here](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-connectedorganizations?view=graph-rest-1.0).
4. Delete the second example
5. I have confirmed that the above request body works
image

**Review by timayabi2020 — CHANGES_REQUESTED** [review]
@merill thanks for noticing this issue.  Here are my suggestions for the example to work as expected.
1.  Roll back to the previous example 1 title.
2.  Since you are targeting to merge into "dev" branch which is responsible for [V1 releases](https://www.powershellgallery.com/packages/Microsoft.Graph/1.28.0), we don't need "-MgBeta" prefix on cmdlets.  Cmdlets with that prefix are only available on [V2 releases](https://www.powershellgallery.com/packages/Microsoft.Graph/2.0.0-rc3) and the branch responsible is "features/2.0".So remove this ``New-MgBetaEntitlementManagementConnectedOrganization -DomainName microsoft.com``.
3.  Update $params with below.
```
$params = @{
	displayName = "Connected organization name"
	description = "Connected organization description"
	identitySources = @(
		@{
			"@odata.type" = "#microsoft.graph.domainIdentitySource"
			domainName = "example.com"
			displayName = "example.com"
		}
	)
	state = "proposed"
}
```
Check Api reference [here](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-connectedorganizations?view=graph-rest-1.0).
4. Delete the second example
5. I have confirmed that the above request body works
image

**Comment by merill** [comment]
@timayabi2020 Using body parameters is not really the best way to do things in PowerShell. Also the other parameters like the name are optional. Do we really need to have them?

Also, is there a reason why we want to remove the second example? I can fix the name of the cmdlet to work with Graph PS v1 beta

**Comment by merill** [comment]
I have put back the body parameter example and also fleshed out the examples. Cheers.

**Review by timayabi2020 — APPROVED** [review]

**Pull request merged**
