### PR TITLE
Stream Support Improvements

### PR DESCRIPTION
**Pull request by peombwa**
This PR proposes the following changes to properly handle file upload and download with the generated commands.

1. Adds `FileUploadCmdlet` class. This will be the base class for all cmdlets that upload files i.e. `-BodyParameter` is of type `Stream` and name starts with `Set-*`. `FileUploadCmdlet` class performs the following :
   - Adds a mandatory `-InFile` parameter to all cmdlets that derive from `FileUploadCmdlet`.
   - `GetFileAsStream` handles getting a resolved path to the file and returns a thread safe stream.
2. Adds `PSCmdletExtensions` class. This class provides helper methods that handle retrieval of valid paths and writing of streams to a file on disk.
3. Adds directives to replace broken file upload and download logic in generated cmdlets. 
    For file download, the directive:
      - Add logic that handles writing of response streams by calling `WriteToFile` in `PSCmdletExtensions`.
  
    For file upload, the directive:
      - Replaces generated base class with `FileUploadCmdlet`.
      - Makes `bodyParameter` optional since `FileUploadCmdlet` adds a mandatory `-InFile` parameter.
      -  Adds logic handles creation of thread safe file upload stream by calling `GetFileAsStream` in `FileUploadCmdlet.
4. Updates modules mapping tags and onpremisespublishingprofile [directives](https://docs.microsoft.com/en-us/graph/api/resources/onpremisespublishingprofile-root?view=graph-rest-beta).

#### Proposed Usage
``` powershell
# Download user profile photo.
Get-MgUserPhotoContent -UserId $userId -OutFile "c:\tmp\profile.png"

# Upload user profile photo.
Set-MgUserPhotoContent -UserId $userId -InFile "c:\tmp\newProfile.png"

# Download drive item content.
Get-MgDriveItemContent -DriveId $driveId -DriveItemId $itemId -OutFile "c:\tmp\doc.docx"

# Upload drive item content.
Set-MgDriveItemContent -DriveId $driveId -DriveItemId $itemId -InFile "c:\tmp\updatedDoc.docx"
```

These changes we tested against the OpenAPI docs in staging. Thanks @irvinesunday!

Closes https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/54 and https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/182

### CODE REVIEW

**Comment by ddyett** [comment]
is this correct?  shouldn't it be infile?

# Upload drive item content.
Set-MgDriveItemContent -DriveId $driveId -DriveItemId $itemId -OutFile "c:\tmp\updatedDoc.docx"

**Comment by ddyett** [comment]
do we need this support for Invoke-GraphRequest too?

**Review by ddyett — APPROVED** [review]

**Comment by finsharp** [comment]
> do we need this support for Invoke-GraphRequest too?

IGR had it baked in, however, I can run the tests @peombwa has run and confirm all is well.

**Review by finsharp — APPROVED** [review]

**Comment by peombwa** [comment]
> is this correct?  shouldn't it be infile?
> 
> 
> 
> # Upload drive item content.
> 
> Set-MgDriveItemContent -DriveId $driveId -DriveItemId $itemId -OutFile "c:\tmp\updatedDoc.docx"

This should be InFile.

**Comment by robinmalik** [comment]
@peombwa What is $itemid in the above examples?

**Pull request merged**
