### PR TITLE
HttpContent disposal causing Null References

### LINKED ISSUE #338: ObjectDisposedException When Running New-Mg* and Update-Mg* cmdlet in PS 5.1
## Steps to reproduce

```powershell
New-MgTeamMember -TeamId $teamId -AdditionalProperties @{"@odata.type" = "microsoft.graph.aadUserConversationMember"; "user@odata.bind" = "https://graph.microsoft.com/beta/users/"+$user.Id} -Roles "owner" -Debug
```

## Expected behavior
`New-MgTeamMember` should succeed without throwing an exception in PowerShell 5.1.

## Actual behavior
`New-MgTeamMember` throws `ObjectDuObjectDisposedException` despite the cmdlet succeeding in PowerShell 5.1.

``` cs
DEBUG: CmdletException: ObjectDisposedException - Cannot access a disposed object.
Object name: 'System.Net.Http.StringContent'. :    at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.ReadAsStreamAsync()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Graph.PowerShell.HttpMessageFormatter.TryComputeLength(Int64& length)
   at System.Net.Http.HttpContent.GetComputedOrBufferLength()
   at System.Net.Http.Headers.HttpContentHeaders.get_ContentLength()
   at System.Net.Http.HttpContent.CreateMemoryStream(Int64 maxBufferSize, Exception& error)
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(Int64 maxBufferSize)
   at System.Net.Http.HttpContent.ReadAsStringAsync()
   at Microsoft.Graph.PowerShell.Module.<Finally>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<EventHandler>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<Signal>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.NewMgTeamMember_CreateExpanded1.<Microsoft-Graph-PowerShell-Runtime-IEventListener-Signal>d__64.MoveNext()
```

## Environment data

```none
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```none
PS C:\WINDOWS\system32> Get-InstalledModule Microsoft.Graph

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
0.9.1      Microsoft.Graph                     PSGallery            Microsoft Graph PowerShell module
```

## Workaround
Use PowerShell 7+ to run the cmdlet. This can be installed from https://github.com/PowerShell/PowerShell/releases.

### PR DESCRIPTION
**Pull request by finsharp**
Serialize all fields except Authorization header.
Load Response into buffer for debug purposes.

Resolves #338 #354

### CODE REVIEW

**Comment by peombwa** [comment]
This issue is still present when executing`Remove-MgApplication -Debug`. Here is a stack trace:
image

It looks like `HttpMessageFormatter` is trying to read a stream (HttpContent) that has already been disposed.

**Review by peombwa — COMMENTED** [review]
The exception is still present with the latest commit (https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/360/commits/0274d2948331449ee38eb90798c53975d9ef0cee). 

Repro steps:
- Clone branch (debugResponseDisposal).
- Generate applications module using `GenerateModule.ps1 -build`.
- Import auth and applications module
  - ` Import-Module .\src\Authentication\Authentication\Microsoft.Graph.Authentication.psd1`
  - ` Import-Module .\src\Applications\Applications\Microsoft.Graph.Applications.psd1`
- Call `Remove-MgApplication -ApplicationId $appId -Debug`. This throws the following exception `Remove-MgApplication_Delete1: The stream was already consumed. It cannot be read again.`.

**Review by peombwa — APPROVED** [review]
LGTM, we should open an issue to ensure we capture all response content. The current fix means that no response will be logged when HttpContent has already been consumed. This is something that AutoREST will need to fix.

**Comment by finsharp** [comment]
> LGTM, we should open an issue to ensure we capture all response content. The current fix means that no response will be logged when HttpContent has already been consumed. This is something that AutoREST will need to fix.

Only requests with no bodies in the response will express this behavior.

**Pull request merged**
