### PR TITLE
Update phoneMethods property is using PUT method

### LINKED ISSUE #278: Trying to use the command Update-MgUserAuthenticationPhoneMethod
I'm trying to bulk update about 5,000 users phone authentication contact info for SSPR but have been unsuccessful at getting it to work. 

  I'm trying to figure out how to right this Graph PowerShell Command command but have been unable to fine any examples on how to do it.  I believe I want to use this command to add or replace users phone number.

Update-MgUserAuthenticationPhoneMethod -UserId 259089c6-10b8-4164-b537-0058b24459b7 -Id 3179e48a-750b-4051-897c-87b9720928f7 -phonenumber "+1 5409446666"

Supply values for the following parameters:
PhoneAuthenticationMethodId:  

I'm not sure what the difference is from "-ID" vs "-PhoneAuthenticationMethodId"

when i use the get-help Update-MgUserAuthenticationPhoneMethod -examples  there is nothing there and no online documentation.  get-help Update-MgUserAuthenticationPhoneMethod -online

Note, i was able to update users using the Graph and this article:  https://techcommunity.microsoft.com/t5/azure-active-directory-identity/manage-your-authentication-phone-numbers-and-more-in-new/ba-p/1257359
 
[AB#7416](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7416)

### PR DESCRIPTION
**Pull request by jbpaux**
Fix #278
According to https://docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&tabs=http the method is PUT not PATCH.
This PR intends to fix thie behavior.
Please update PowerShell module then.

### CODE REVIEW

**Comment by ddyett** [comment]
the right fix is to fix the OpenAPI generation. @peombwa we can temporarily unblock for the next release but we'd have to manually check that we don't overwrite the change.  I've moved the priority of the OpenAPI change up.

**Comment by darrelmiller** [comment]
@jbpaux  Can you let us know when the API has implemented PATCH for doing updates so that we can close this PR.

**Comment by jbpaux** [comment]
@darrelmiller How can I know it was updated ? :cry: I think it's internal MS stuff.

**Comment by darrelmiller** [comment]
@jbpaux Oops. Sorry about that.  I thought you were from that team.

**Review by andrewchoi5 — APPROVED** [review]

**Comment by jbpaux** [comment]
I guess this won't merge so I'll close it.

**Pull request closed without merging**
