### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by MIchaelMainer**
Part of component governance review

### CODE REVIEW

**Comment by peombwa** [comment]
Thanks for surfacing this! To avoid [PowerShell assembly dependency conflicts](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.2), we will need to investigate how this can be safely used with our [assembly resolver](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Authentication/Authentication/Utilities/DependencyAssemblyResolver.cs#L14).

**Comment by MIchaelMainer** [comment]
Interesting. As it is currently, the automated use of dependabot would then trigger manual changes to the PowerShell Assembly Load Context every time a dependency is out of date, correct?

**Comment by peombwa** [comment]
That's right! It looks like we will need a post dependabot script to ensure dependencies are also updated in the PowerShell Assembly Load Context. I can look into this.

**Comment by MIchaelMainer** [comment]
Required reading for this work item.

https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by baywet** [comment]
closing since this was added through another PR https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/a96b7721eda502401e92b2f81cb6adeef5545adc/.github/dependabot.yml#L1

**Pull request closed without merging**
