### PR TITLE
 - adds docker image definition

### PR DESCRIPTION
**Pull request by baywet**
template for CD https://github.com/microsoft/kiota/blob/main/.github/workflows/docker.yml

### CODE REVIEW

**Review by peombwa — APPROVED** [review]
:shipit:

**Comment by shurick81** [comment]
Is CD also implemented? Probably some update in documentation of Microsoft.Graph that is referring to a public Docker image won't hurt? I would be happy to know at least the image name :)

**Comment by baywet** [comment]
Thanks for the reminder. We do have CD in place to our ACR last time I checked. However I was out last week as we were preparing to get approval from the team in charge of the mcr. @peombwa did your PRs to mcr and mcr docs make it through?

**Comment by peombwa** [comment]
@baywet, we put the PR on hold to unblock #1330. We will resume the mcr work once the release is out.

**Pull request merged**
